### ISSUE TITLE
Week 1: Designs, HTML, & CSS

### ISSUE THREAD

**Issue by evanfrawley** [TeamMoodGitHub/Alden-Term-1#1]
Project: OP.GG Clone w/ some algorithms with MMR down the line 🎮 

OP.GG is a website that's interactive. If you're gonna make something similar, your stuff has to interactive too, so let's learn how to make the foundation of an interactive website!

1. _**Wireframes**_ - Understanding what the site will (generally) look like. When coding up something, it is *much* easier to create it with something to work off of -- even though often times these designs won't look exactly like the final version, nor will be super flushed out. Regardless, they're still super useful to use!
2. _**HTML / CSS**_ - Researching & understanding how HTML / CSS work. This is the bread and butter of websites (and we'll start exploring Javascript next week). I want you to take some time to learn how HTML / CSS work, and how you can go about constructing a webpage from scratch using them!

So here are your action items to complete this week:
- [ ] Create initial barebones designs ("wireframes") of all the "views" (individual pages) that you think your site would have. You can create wireframes using [Balsamiq](https://balsamiq.com/) for free! When you've completed the wireframes, please comment them directly to this issue!
- [ ] Do some HTML / CSS tutorial(s). I'd recommend doing this [one](https://www.codecademy.com/learn/web) and working through enough until you're comfortable with HTML & CSS and have a solid understanding with how they work. Feel free to use Github to host your practice HTML / CSS files!

Next week, I'm looking at having you start to learn Javascript, and how JS makes your site interactive, so that you can do way cooler shit than just HTML / CSS.

With this -- GLHF! :fire: Please feel free to reach out to me if you have questions about any of the above 😄 I'm really excited to see what you'll be able to do with the data from League!

**Comment by heyitsalden** [comment]
This week I've put in time creating the wire frames for the website and have been getting familiar with HTML and CSS through CodeAcademy. With school now a responsibility to manage, I have a little less wiggle room to use however, I feel like I would still accomplish future tasks. With the wire frames, I feel more confident with the vision of the website I want to pursue and hopefully when I finish getting familiar with HTML and CSS, I will be able to start the process of creating the website I envisioned.
